package com.example.employee.model.entity;
// Generated Nov 26, 2019, 10:07:59 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Agama generated by hbm2java
 */
@Entity
@Table(name = "agama", schema = "public")
public class Agama implements java.io.Serializable {

	private long idAgama;
	private String namaAgama;
	private Set<Karyawan> karyawans = new HashSet<Karyawan>(0);

	public Agama() {
	}

	public Agama(long idAgama, String namaAgama) {
		this.idAgama = idAgama;
		this.namaAgama = namaAgama;
	}

	public Agama(long idAgama, String namaAgama, Set<Karyawan> karyawans) {
		this.idAgama = idAgama;
		this.namaAgama = namaAgama;
		this.karyawans = karyawans;
	}

	@Id
	@SequenceGenerator(name="agama_seq_gen", sequenceName="agama_id_seq", schema = "public", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "agama_seq_gen")
	@Column(name = "`ID_AGAMA`", unique = true, nullable = false)
	public long getIdAgama() {
		return this.idAgama;
	}

	public void setIdAgama(long idAgama) {
		this.idAgama = idAgama;
	}

	@Column(name = "`NAMA_AGAMA`", nullable = false, length = 128)
	public String getNamaAgama() {
		return this.namaAgama;
	}

	public void setNamaAgama(String namaAgama) {
		this.namaAgama = namaAgama;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agama")
	public Set<Karyawan> getKaryawans() {
		return this.karyawans;
	}

	public void setKaryawans(Set<Karyawan> karyawans) {
		this.karyawans = karyawans;
	}

}
