package com.example.employee.model.entity;
// Generated Nov 26, 2019, 10:07:59 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListKemampuan generated by hbm2java
 */
@Entity
@Table(name = "list_kemampuan", schema = "public")
public class ListKemampuan implements java.io.Serializable {

	private long idListKemampuan;
	private Karyawan karyawan;
	private Kemampuan kemampuan;
	private Integer nilaiKemampuan;

	public ListKemampuan() {
	}

	public ListKemampuan(long idListKemampuan) {
		this.idListKemampuan = idListKemampuan;
	}

	public ListKemampuan(long idListKemampuan, Karyawan karyawan, Kemampuan kemampuan, Integer nilaiKemampuan) {
		this.idListKemampuan = idListKemampuan;
		this.karyawan = karyawan;
		this.kemampuan = kemampuan;
		this.nilaiKemampuan = nilaiKemampuan;
	}

	@Id

	@Column(name = "ID_LIST_KEMAMPUAN", unique = true, nullable = false)
	public long getIdListKemampuan() {
		return this.idListKemampuan;
	}

	public void setIdListKemampuan(long idListKemampuan) {
		this.idListKemampuan = idListKemampuan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_KARYAWAN")
	public Karyawan getKaryawan() {
		return this.karyawan;
	}

	public void setKaryawan(Karyawan karyawan) {
		this.karyawan = karyawan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_KEMAMPUAN")
	public Kemampuan getKemampuan() {
		return this.kemampuan;
	}

	public void setKemampuan(Kemampuan kemampuan) {
		this.kemampuan = kemampuan;
	}

	@Column(name = "NILAI_KEMAMPUAN")
	public Integer getNilaiKemampuan() {
		return this.nilaiKemampuan;
	}

	public void setNilaiKemampuan(Integer nilaiKemampuan) {
		this.nilaiKemampuan = nilaiKemampuan;
	}

}
