package com.example.employee.model.entity;
// Generated Nov 26, 2019, 10:07:59 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId implements java.io.Serializable {

	private long idUser;
	private String username;

	public UserId() {
	}

	public UserId(long idUser, String username) {
		this.idUser = idUser;
		this.username = username;
	}

	@Column(name = "ID_USER", nullable = false)
	public long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(long idUser) {
		this.idUser = idUser;
	}

	@Column(name = "USERNAME", nullable = false, length = 128)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserId))
			return false;
		UserId castOther = (UserId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdUser();
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
